dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    usdt_usd_price_feed: '0xa24de01df22b63d23Ebc1882a5E3d4ec0d907bFB'
    usdc_usd_price_feed: '0xa24de01df22b63d23Ebc1882a5E3d4ec0d907bFB'
  mainnet-fork:
    usdt_usd_price_feed: '0x3e7d1eab13ad0104d2750b8863b489d65364e32d'
    usdc_usd_price_feed: '0x8fffffd4afb6115b954bd326cbe7b4ba576818f6'